# Book settings

title: WP5docs
author: Francesco Giuseppe Gravili
logo: "icsc.png"
copyright: "2024"

# Force re-execution of notebooks on each build
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  use_jupyterbook_latex: false
  latex_documents:
    targetname: UserGuide.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/frgigr/testbook
  branch: main

    # Add repository buttons to your book: issues not supported by GitLab
html:
  use_issues_button: false
  use_repository_button: false
  announcement: "Version 0.1"
