# Basic workflow to get started with Actions
name: JupyterBook

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# List of one or more jobs that can run sequentially or in parallel
jobs:
  # Build step
  buildjob:
    name: Building documentation
    
    # Select ubuntu, LTS version
    runs-on: ubuntu-22.04

    # Full sequence of tasks being executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Setup python 3.10
      - name: Python 3 setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Verify the installation is complete, with no issues
      - name: Display python version
        run: python -c "import sys; print(sys.version)"

      # Install jupyter book package
      - name: Install additional packages
        run: pip install jupyter-book
  
      # Compile the documentation
      - name: Building documentation
        run: jupyter-book build docs/

      # Configure pages
      - name: Setup pages
        id: pages
        uses: actions/configure-pages@v3
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site    
  
      # Upload artifacts
      - name: Upload artifacts after building
        uses: actions/upload-pages-artifact@v2
        with:
          name: builtDocs
          path: docs/_build/
          retention-days: 1

  deploy:
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page-url}}
    runs-on: ubuntu-22.04
    needs: buildjob
    steps:
      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v2
